### PR TITLE
converted to psr4 composer library

### PR DESCRIPTION
**Pull request by w3guy**
@Kubitomakita @XedinUnknown Thoughts?

### CODE REVIEW

**Comment by XedinUnknown** [comment]
That's much better. Didn't understand why the _package.json_ though.

**Comment by XedinUnknown** [comment]
Also, I would explicitly define the required PHP version.

**Comment by w3guy** [comment]
> Also, I would explicitly define the required PHP version.
On composer.json file right?

**Comment by XedinUnknown** [comment]
@collizo4sky, yeap.

**Comment by w3guy** [comment]
Could you give the json name and value to do that?

Seem to have forgotten.

**Comment by XedinUnknown** [comment]
Sure, [here you go](http://lmgtfy.com/?q=composer+schema+require). FYI, I am a certified Google operator.

**Comment by w3guy** [comment]
What does it mean to be "certified Google operator" ? Hearing that for the first time.

**Comment by XedinUnknown** [comment]
It means I was specially trained to use the Google search. So, when you feel that you find it difficult to use this sophisticated Google feature, feel free to ask me, and I will google for you.

**Comment by jakubmikita** [comment]
Thanks @XedinUnknown for your input and @collizo4sky for your PRs.

Unfortunately, I cannot merge this one because it's far far away from my workflow and doesn't meet my own requirements ;)

I'm glad that became a foundation for your fork, though. I hope it will work well in your projects.

**Comment by w3guy** [comment]
No problem Kuba.

**Pull request closed without merging**
