### PR TITLE
Translations support

### PR DESCRIPTION
**Pull request by dmhendricks**
I was hoping for translation support for my plugins that use it as a dependency, so I made some changes. My plugins are translated, but when Requirements throws an error, it is in English.

- Added i18n support
- Added string translations for Español
- Modified package.json because npm was complaining about the slash in the name and that the version wasn't semver (feel free to re-add it, but it broke npm for me)
- Added `npm run translate` to regenerate .pot file using [wp-pot-cli](https://www.npmjs.com/package/wp-pot-cli)
- Added extra lines to .gitignore due to added npm cruft
- Added private string $textdomain to hold translation domain
- Bumped version to 1.3.0 due to translation support (feel free to revert)
- Minor verbiage tweaks (feel free to revert/modify)

I can possibly help with additional translations, if desired, or other changes.

Feedback welcome and thank you,
Daniel

EDIT: Sorry I didn't PR to develop branch.

### CODE REVIEW

**Comment by jakubmikita** [comment]
Thank you for your contribution Daniel! I'll merge it to the `develop` and do the proper release but otherwise looks good!

How do you load the translation for the lib? Maybe you could include a simple snippet in readme?

**Comment by dmhendricks** [comment]
Oops, I must have forgotten to check in that change. Give me some time and I will add. I have it loading in `underDEV_Requirements.php`, so no extra code necessary.

**Comment by dmhendricks** [comment]
Sorry about that - I missed a commit. It's there now. I'd like to add translations for some of the more popular languages if this is merged.

I'm already using the translated version in [one of my plugins](https://wordpress.org/plugins/my-sites-sort-and-filter/) and would like additional translations so that the [percentages](https://translate.wordpress.org/projects/wp-plugins/my-sites-sort-and-filter) are on par. Fortunately, there aren't many strings to translate so it's mostly easy.

**Comment by jakubmikita** [comment]
Thanks for the commit Daniel, one question though - why not `load_plugin_textdomain()` but `load_textdomain()`?

Also, my concern is when the translation is loaded. Wouldn't it fail if called before the `init` action?

EDIT: When I sent the comment it struck me that it's not a plugin... sorry! But the second question is valid :)

**Comment by dmhendricks** [comment]
I'm not sure if there is a more appropriate time to load it, but it is working with the plugin that I'm using it on (autoloaded via Composer). I just switched to Español and triggered an error on plugin activation which returned the appropriate translated strings from Requirements:

screen shot 2018-09-16 at 10 04 44 pm

EDIT 2018/09/16: Tested German, Français -

screen shot 2018-09-16 at 11 35 35 pm

screen shot 2018-09-16 at 11 45 32 pm

**Comment by jakubmikita** [comment]
Awesome, thanks!

I'm merging this right now to `develop` and I'll remove the version bumps etc.

Let me know if you wish to add something more or I should release.

**Comment by dmhendricks** [comment]
I'd like to add Portuguese and Italian. I'm also hoping for/waiting on Russian translation. I predict that I can have all 3 of those done in the next 24-36 hours, but it depends when the translation service gets back to me (I had another thing to translate in Russian and threw in the strings from Requirements, as well as a third project, but they are usually fast).

**Comment by jakubmikita** [comment]
No worries, I can wait :)

**Pull request merged**
