### PR TITLE
Real composer (autoloading) support

### PR DESCRIPTION
**Pull request by w3guy**

### CODE REVIEW

**Comment by w3guy** [comment]
As per my comment on AWP thread announcing this lib.

**Comment by jakubmikita** [comment]
Thanks @collizo4sky but what will happen if someone will use Composer lib with the minimum requirement of PHP 7 on some older PHP?

Checks will not fire up before the fatal error I think.

**Comment by w3guy** [comment]
I don't seem to get your question.

This pull request eliminate the need of using `require_once` or `require` and allows composer to do the autoloading such that including `vendor/autoload.php` is enough to include this lib (any any composer lib a project uses).

It is one and the same with using `require`

**Comment by w3guy** [comment]
@Kubitomakita see https://github.com/collizo4sky/persist-admin-notices-dismissal/blob/master/composer.json

**Comment by jakubmikita** [comment]
Yes, the idea is good but may cause the errors in some cases. In example let's say you have in your project libs:

```
"require": {
  'underdev/requirements': '*',
  'some/lib: '*'
},
```

and `some/lib` have a requirement of PHP 7 and also loads some files right a way.

In your plugin, you want to check the requirements of PHP 7 with `underDEV_Requirements` class. But as soon you will call `require_once( 'vendor/autoload.php' )` it will throw a fatal error in environment with PHP<7.

**Comment by w3guy** [comment]
Composer packages are meant to not load (in case of class, instantiate themselves in same file) themselves right away. That is bad practice.

It should only define the class(es) and method to implement.

Then the implementer will `require vendor/autoload.php`

And finally instantiate/use the composer package in her project.

FWIW, i see lot's of plugins, even big plugins like WC instantiate classes at the bottom of the class file and it is wrong.

You shouldn't cater for dev programming wrongly. You can advice them / show them the right way though.

**Comment by jakubmikita** [comment]
Ok, I can see your point but still I'm worrying about the conflicts with other libs.

Let's vote. In the first comment, I added a 👍 and 👎 reactions. Users will decide if this is a good idea to merge or no.

**Comment by XedinUnknown** [comment]
When you use `files`, the files there will be loaded as soon as you include `autoload.php`. Instead, use [`classmap`](https://getcomposer.org/doc/04-schema.md#classmap).

**Comment by w3guy** [comment]
@XedinUnknown pls submit a quick PR using Github website.

**Comment by XedinUnknown** [comment]
Sorry, no time. Also, no point. There are so many things wrong with this code that it's not worth fixing. I'm just trying to help the author understand where he went wrong, so that he can make better software in the future.

On the subject, why not simply use PSR-4? Solves all autoloading problems forever.

**Comment by w3guy** [comment]
Since this is a single file, i think using `files` is better.

**Comment by w3guy** [comment]
@XedinUnknown I will find time this evening to make this a complete composer package with namespace correct psr 4 autoloading

**Comment by XedinUnknown** [comment]
@collizo4sky, I'm telling you: `files` will load the file immediately. You don't want that. Author already pointed out the potential problem. `classmap` solves that problem in a dirty way. `psr-4` solves it in a clean way.

**Comment by jakubmikita** [comment]
@XedinUnknown can you elaborate what's wrong with my code? I just want to made it super flexible and working in every environment. That's why no PSR or namespacing.

But you are right, `classmap` is better, I'll load it this way.

**Comment by dawidurbanski** [comment]
@XedinUnknown `psr-4`, is not an option with this little library. It's intention is to check requirements, so as I assume it should work also in legacy environment (like `php 5.2`).

Anyway `classmap` seems to be the only option here.

**Comment by XedinUnknown** [comment]
@DawidUrbanski, Composer [requires](https://getcomposer.org/doc/00-intro.md#system-requirements) PHP 5.3.2. PHP 5.2 is [EOL](http://php.net/eol.php) in 2011, and is used by < 5% of WP sites, of which the majority is most likely simply abandoned. WP [recommends](https://wordpress.org/about/requirements/) PHP >= 7.0. Just forget it, and program properly.

**Comment by XedinUnknown** [comment]
@Kubitomakita, your code is *not* flexible, at the very least because it requires extension of the class to support checks other than what you have built in.

**Comment by jakubmikita** [comment]
@XedinUnknown Composer required PHP 5.3.2, yes, but this lib was initially a drop-in. You don't have to use Composer.

I'd say extending a class is pretty flexible. I see no point in making any interfaces to do a simple thing like this class do.

**Comment by w3guy** [comment]
Everyone see #2

**Comment by XedinUnknown** [comment]
Here's my take on the best requirements lib ever. Feel free to use for any purpose.

```php
```

Benefits:
- You can extend this code however you want, even using other languages.
- Completely 100% bug free.
- 100% test code coverage.
- 100% compatible with any other lib.
- Compatible with WordPress. Oh, who are we kidding: compatible with PHP 1.0.
- No need for Composer.

**Comment by dawidurbanski** [comment]
@XedinUnknown All jokes aside. What is the point of lib for checking php version if it cant handle old legacy environment? Is this not the point of whole library? Not everything in this world is supposed to be written in most modern fashion.

This is written for WordPress. And WordPress states that `WordPress also works with PHP 5.2.4+`. Untill that changes, lib like this one should support all scenarios. If you feel it's not for you, fork it and make it your way.

**Comment by jakubmikita** [comment]
Amen.

**Pull request closed without merging**
